stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "unix:///runner/services/docker/docker.sock"

build-rest:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--mtu=1500"]
  before_script:
    - echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
    - apk add --no-cache nodejs npm bash jq
  script:
    - cd amaterasu-rest
    - npm run docker:build
  tags:
    - docker

build-web:
  stage: build
  image: docker:24.0.7
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--mtu=1500"]
  before_script:
    - echo $DOCKER_HUB_ACCESS_TOKEN  | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
    - apk add --no-cache nodejs npm bash jq
  script:
    - cd amaterasu-web
    - npm run docker:build
  tags:
    - docker

deploy:
  stage: deploy
  image: docker:latest
  services:
    - name: docker:dind
      command: ["--host=tcp://0.0.0.0:2375", "--mtu=1500"]
  before_script:
    - apk add --no-cache bash curl python3 py3-pip py3-paramiko
  script:
    - eval $(ssh-agent -s)
    - mkdir ~/.ssh
    - ssh-keyscan -H $STAGE_SERVER_IP >> ~/.ssh/known_hosts
    - echo "$STAGE_SERVER_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - export DOCKER_HOST=ssh://$STAGE_SERVER_USER@$STAGE_SERVER_IP
    - docker compose down --remove-orphans
    - docker compose pull
    - docker compose up -d
  tags:
    - docker
  dependencies:
    - build-rest
    - build-web
  when: manual
