stages:
  - build
  - deploy

build-rest:
  stage: build
  image: docker:24.0.7 
  before_script:
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
    - apk add --no-cache nodejs npm
  script:
    - cd amaterasu-rest
    - npm run docker:build
  tags:
    - docker

build-web:
  stage: build
  image: docker:24.0.7
  before_script:
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
    - apk add --no-cache nodejs npm
  script:
    - cd amaterasu-web
    - npm run docker:build
  tags:
    - docker

deploy:
  stage: deploy
  image: ubuntu:latest # Use a base image with necessary tools
  services:
    - docker:dind
  before_script:
    - apt-get update -y
    - apt-get install -y kubectl curl
    - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - install minikube-linux-amd64 /usr/local/bin/minikube
    - minikube start --driver=docker
    - export KUBECONFIG=$HOME/.kube/config
    - kubectl cluster-info
  script:
    - kubectl apply -f kubernetes/deployment.yaml
    - kubectl apply -f kubernetes/service.yaml
  tags:
    - docker
  dependencies:
    - build-rest
    - build-web
  when: manual