services:
  amaterasu-web:
    image: infernokun/amaterasu-web
    #build: ./amaterasu-web
    restart: always
    environment:
      - BASE_URL=http://amaterasu-web
      - REST_URL=/api
    ports:
      - "8764:80"
    depends_on:
      amaterasu-db:
        condition: service_healthy

  amaterasu-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-amaterasu}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-amaterasu}"
      POSTGRES_DB: "${POSTGRES_DB:-amaterasu}"
    volumes:
      - ./amaterasu-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-amaterasu}"]
      interval: 10s
      timeout: 5s
      retries: 5

  amaterasu-rest:
    image: infernokun/amaterasu-rest
    #build: ./amaterasu-rest
    restart: always
    ports:
      - "8765:8080"
    environment:
      DOCKER_COMPOSE_PATH: "${DOCKER_COMPOSE_PATH:-/var/tmp/amaterasu}"
      DB_IP: "${POSTGRES_IP:-amaterasu-db}"
      DB_NAME: "${POSTGRES_DB:-amaterasu}"
      DB_USER: "${POSTGRES_USER:-amaterasu}"
      DB_PASS: "${POSTGRES_PASSWORD:-amaterasu}"
      DB_PORT: "${DB_PORT:-5432}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY:-secret_key}"
    depends_on:
      - amaterasu-db
    