services:
  amaterasu-web:
    image: infernokun/amaterasu-rest
    #build: ./amaterasu-web
    restart: always
    ports:
      - "80:80"
    depends_on:
      - amaterasu-rest
  amaterasu-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./amaterasu-db:/var/lib/postgresql/data
  amaterasu-rest:
    image: infernokun/amaterasu-rest
    #build: ./amaterasu-rest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DOCKER_COMPOSE_PATH=/app/amaterasu
      - DB_IP=${DB_IP}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_PORT=${DB_PORT}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    depends_on:
      - amaterasu-db
    