services:
  amaterasu-web:
    build: ./amaterasu-web
    restart: always
    ports:
      - "443:443"
    depends_on:
      - amaterasu-db
  amaterasu-db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=amaterasu
      - POSTGRES_PASSWORD=amaterasu
      - POSTGRES_DB=amaterasu
    volumes:
      - ./amaterasu-db:/var/lib/postgresql/data
  amaterasu-rest:
    build: ./amaterasu-rest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DOCKER_COMPOSE_PATH=/app/amaterasu
      - DOCKER_IP=amaterasu
      - DOCKER_USER=amaterasu
      - DOCKER_PASS=amaterasu
      - DB_USER=infernokun
      - DB_PASS=amaterasu
    depends_on:
      - amaterasu-db
    