version: '3.8'

services:
  app:
    image: node:18
    container_name: node_app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: ["node", "server.js"]
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer_ui
    ports:
      - "8081:8080"
    restart: always
    depends_on:
      - db

volumes:
  db_data:
