export enum LabStatus {
  NONE = 'NONE',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  HIDDEN = 'HIDDEN',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  DELETED = 'DELETED',
  STOPPED = 'STOPPED',
  RETIRED = 'RETIRED',
  FAILED = 'FAILED',
}
